// packages/react/src/bindField.ts
import type { FieldAtom, Rec } from '@reatom/core'
import { memoKey, notify, wrap } from '@reatom/core'
import type { ChangeEvent } from 'react'

export function bindField<T = any>(
  field: FieldAtom<any, T>,
): {
  value: T
  checked: T extends boolean ? boolean : undefined
  onChange: (
    value:
      | T
      | { currentTarget: T extends boolean ? { checked: T } : { value: T } }
      | ChangeEvent<{ value: T }>,
  ) => void
  onBlur: () => void
  onFocus: () => void
  error: undefined | string
} {
  const value = field()

  const { onChange, onBlur, onFocus } = memoKey(field.name, () => {
    const onChange = wrap((event: any) => {
      const isEvent = !!event?.currentTarget?.addEventListener
      const value = isEvent
        ? event.currentTarget.type === 'checkbox'
          ? event.currentTarget.checked
          : event.currentTarget.value
        : event

      field.change(value)
      notify()
    })

    const onBlur = wrap(() => {
      field.focus.out()
      notify()
    })
    const onFocus = wrap(() => {
      field.focus.in()
      notify()
    })

    return { onChange, onBlur, onFocus }
  })

  const { error } = field.validation()

  const result: Rec = {
    onChange,
    onBlur,
    onFocus,
    error,
  }

  if (typeof value === 'boolean') {
    result.checked = value
  } else {
    result.value = value
  }

  // @ts-expect-error generic overloads
  return result
}

// packages/solid-js/src/bindField.ts
import type { FieldAtom, FieldValidation } from '@reatom/core'
import { notify, wrap } from '@reatom/core'
import type { Accessor } from 'solid-js'

import { useAtom, useFrame } from './index'

export function bindField<T = any>(
  field: FieldAtom<any, T>,
): {
  value: Accessor<T>
  validation: Accessor<FieldValidation>
  props: {
    value: T extends boolean ? undefined : T
    checked: T extends boolean ? boolean : undefined
    onChange: (
      value:
        | T
        | { currentTarget: T extends boolean ? { checked: T } : { value: T } }
        | Event,
    ) => void
    onBlur: () => void
    onFocus: () => void
  }
} {
  const frame = useFrame()

  const onChange = wrap((event: any) => {
    const isEvent = !!event?.currentTarget?.addEventListener
    const value = isEvent
      ? event.currentTarget.type === 'checkbox'
        ? event.currentTarget.checked
        : event.currentTarget.value
      : event

    field.change(value)
    notify()
  }, frame)

  const onBlur = wrap(() => {
    field.focus.out()
    notify()
  }, frame)

  const onFocus = wrap(() => {
    field.focus.in()
    notify()
  }, frame)

  const [valueAccessor] = useAtom(field.value)
  const [validationAccessor] = useAtom(field.validation)

  const props = {
    onChange,
    onBlur,
    onFocus,
    get value() {
      const value = valueAccessor()
      return (
        typeof value === 'boolean' ? undefined : value
      ) as T extends boolean ? undefined : T
    },
    get checked() {
      const value = valueAccessor()
      return (
        typeof value === 'boolean' ? value : undefined
      ) as T extends boolean ? boolean : undefined
    },
  }

  return {
    value: valueAccessor,
    validation: validationAccessor,
    props,
  }
}
